baseURL: https://shruti2062.github.io/
languageCode: en-us
build:
  writeStats: true
params:
  title: Shruti's Portfolio
  author: Shruti Sharma
  description: Website title
  theme:
    mainTheme: light
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Shruti Sharma"
    tagline: Research Scholar
    location: "India"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/shruti-sharma-592075226"
        title: LinkedIn
      - icon: fab fa-orcid
        url: "https://orcid.org/0009-0005-4259-7348"
        title: Orcid
      - icon: ai ai-google-scholar
        url: "https://scholar.google.com/citations?user=8KN7rKQAAAAJ&hl=en"
        title: Google Scholar
      - icon: fab fa-researchgate
        url: "https://www.researchgate.net/profile/Shruti-Sharma-124?ev=hdr_xprf"
        title: ResearchGate
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: I am currently pursuing a Ph.D. in the field of nanoscience and technology, focusing on the synthesis and characterization of Carbon Quantum Dots (CQDs) using cost-effective techniques with various non-toxic green and organic precursors. To enhance their efficiency and stability, these CQDs are capped with organic polymers. My research explores their applications in nanosensors, bioimaging, and light-emitting devices. I have published eight research papers, including six as the first author in reputed journals, and have presented my work at multiple national and international conferences. 
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Ph.D. Research Scholar
        dates: 2022 - Present
        company: Jaypee Institute of Information Technology, Noida secor-62, Uttar Pradesh India
        details: |1-
          - synthesis and characterization of Carbon Quantum Dots (CQDs) using cost-effective techniques with various non-toxic green and organic precursors.
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: Ph.D. in Physics
        college: Jaypee Institute of Information Technology, Noida secor-62, Uttar Pradesh, India
        dates: 2022 - Present
        thesis_title: "Carbon Quantum Dots (CQDs) synthesis, characterization and applications."
        thesis_url: "#"
      - degree: M.Sc. in Physics 
        college: Kirorimal College, University of Delhi, New Delhi India
        dates: 2020 - 2022
        thesis_title: "Proton acceleration from laser-solid interaction via pic simulations."
        thesis_url: "#"
      - degree: B.S. in Physics (Honours)
        college: Shaheed Rajguru College of Applied Sciences for Women, University of Delhi, New Delhi, India
        dates: 2017 - 2020
  publication:
    title: Publications
    icon: fas fa-book
    format:
      - date
      - title
      - authors
      - journal
    types:
      - Journal Articles
      - Proceedings
    list:
      - title: >-
          Harvesting Nature's Brilliance: Iron Ion (Fe3+) Sensing by Plumeria obtusa Leaf-Derived Carbon Quantum Dots.
        authors: "Shruti Sharma, Amisha Bhardwaj, Narayanan Venkatakrishnan, Papia Chowdhury"
        date: "2024"
        journal: "Arabian Journal for Science and Engineering"
        url: "https://doi.org/10.1007/s13369-024-09815-8"
        type: Journal Articles
      - title: >-
          Reactivities of 4-amino salicylic acid and its ‘Green’inhibition into nano sized β-cyclodextrin for Anti-Tuberculosis drug delivery.
        authors: "Shruti Sharma, Pooja Yadav, Meenakshi Rana, Papia Chowdhury"
        date: "2024"
        journal: "Journal of Molecular Liquids, 410, 125611"
        url: "https://doi.org/10.1016/j.molliq.2024.125611"
        type: Journal Articles
      - title: >-
          Photoluminescent carbon quantum dots synthesized from Plumeria leaves as metal ion sensor.
        authors: "Shruti Sharma, Papia Chowdhury"
        date: "2024"
        journal: "Bulletin of Materials Science 47 (3), 187"
        url: "https://doi.org/10.1007/s12034-024-03273-6"
        type: Journal Articles
      - title: >-
          Tunable dual photoluminescence from synthesized urea-based carbon quantum dots: A DFT based simulation on structural insights.
        authors: "Shruti Sharma, Papia Chowdhury"
        date: "2024"
        journal: "Optical Materials, 153, 115617"
        url: "https://doi.org/10.1016/j.optmat.2024.115617"
        type: Journal Articles
      - title: >-
          Thioglycolic acid capped CdSe/ZnS quantum dot as fluorescent sensor for the detection of water-soluble hazardous heavy metal ions.
        authors: "Shruti Sharma, Pooja Yadav, Papia Chowdhury"
        date: "2024"
        journal: "Applied Physics A 130 (5), 1-12"
        url: "https://doi.org/10.1007/s00339-024-07491-x"
        type: Journal Articles
      - title: >-
          Two-photon absorption and optical limiting in 7-diethylamino-4-methyl coumarin.
        authors: "Shradha Lakhera, Kamal Devlal, Meenakshi Rana, N Kanagathara, A Dhanusha, TC Sabari Girisun, Shruti Sharma, Papia Chowdhury"
        date: "2024"
        journal: "Journal of Photochemistry and Photobiology A: Chemistry 447, 115216"
        url: "https://doi.org/10.1016/j.jphotochem.2023.115216"
        type: Journal Articles
        type: Journal Articles
      - title: >-
          Exploring the nonlinear optical limiting activity of para-aminobenzoic acid by experimental and DFT approach.
        authors: "Shradha Lakhera, Meenakshi Rana, Kamal Devlal, Shruti Sharma, Papia Chowdhury, Vivek Dhuliya, Sagar Panwar, LP Purohit, A Dhanusha, TC Sabari Girisun"
        date: "2023"
        journal: "Journal of Photochemistry and Photobiology A: Chemistry, 444, 114987"
        url: "https://doi.org/10.1016/j.jphotochem.2023.114987"
        type: Journal Articles
      - 
        title: >-
          Fluorescence signal from carbon quantum dots synthesized from natural resources.
        authors: "Shruti Sharma, Papia Chowdhury"
        date: "2023"
        journal: "Materials Today: Proceedings"
        url: "https://doi.org/10.1016/j.matpr.2023.05.676"
        type: Proceedings
    publication:
    title: Publications
    icon: fas fa-book
    format:
      - date
      - title
      - authors
      - journal
    types:
      - Journal Articles
      - Proceedings
    list:
      - title: >-
          Harvesting Nature's Brilliance: Iron Ion (Fe3+) Sensing by Plumeria obtusa Leaf-Derived Carbon Quantum Dots.
        authors: "Shruti Sharma, Amisha Bhardwaj, Narayanan Venkatakrishnan, Papia Chowdhury"
        date: "2024"
        journal: "Arabian Journal for Science and Engineering"
        url: "https://doi.org/10.1007/s13369-024-09815-8"
        type: Journal Articles
      - title: >-
          Reactivities of 4-amino salicylic acid and its ‘Green’inhibition into nano sized β-cyclodextrin for Anti-Tuberculosis drug delivery.
        authors: "Shruti Sharma, Pooja Yadav, Meenakshi Rana, Papia Chowdhury"
        date: "2024"
        journal: "Journal of Molecular Liquids, 410, 125611"
        url: "https://doi.org/10.1016/j.molliq.2024.125611"
        type: Journal Articles
      - title: >-
          Photoluminescent carbon quantum dots synthesized from Plumeria leaves as metal ion sensor.
        authors: "Shruti Sharma, Papia Chowdhury"
        date: "2024"
        journal: "Bulletin of Materials Science 47 (3), 187"
        url: "https://doi.org/10.1007/s12034-024-03273-6"
        type: Journal Articles
      - title: >-
          Tunable dual photoluminescence from synthesized urea-based carbon quantum dots: A DFT based simulation on structural insights.
        authors: "Shruti Sharma, Papia Chowdhury"
        date: "2024"
        journal: "Optical Materials, 153, 115617"
        url: "https://doi.org/10.1016/j.optmat.2024.115617"
        type: Journal Articles
      - title: >-
          Thioglycolic acid capped CdSe/ZnS quantum dot as fluorescent sensor for the detection of water-soluble hazardous heavy metal ions.
        authors: "Shruti Sharma, Pooja Yadav, Papia Chowdhury"
        date: "2024"
        journal: "Applied Physics A 130 (5), 1-12"
        url: "https://doi.org/10.1007/s00339-024-07491-x"
        type: Journal Articles
      - title: >-
          Two-photon absorption and optical limiting in 7-diethylamino-4-methyl coumarin.
        authors: "Shradha Lakhera, Kamal Devlal, Meenakshi Rana, N Kanagathara, A Dhanusha, TC Sabari Girisun, Shruti Sharma, Papia Chowdhury"
        date: "2024"
        journal: "Journal of Photochemistry and Photobiology A: Chemistry 447, 115216"
        url: "https://doi.org/10.1016/j.jphotochem.2023.115216"
        type: Journal Articles
        type: Journal Articles
      - title: >-
          Exploring the nonlinear optical limiting activity of para-aminobenzoic acid by experimental and DFT approach.
        authors: "Shradha Lakhera, Meenakshi Rana, Kamal Devlal, Shruti Sharma, Papia Chowdhury, Vivek Dhuliya, Sagar Panwar, LP Purohit, A Dhanusha, TC Sabari Girisun"
        date: "2023"
        journal: "Journal of Photochemistry and Photobiology A: Chemistry, 444, 114987"
        url: "https://doi.org/10.1016/j.jphotochem.2023.114987"
        type: Journal Articles
      - 
        title: >-
          Fluorescence signal from carbon quantum dots synthesized from natural resources.
        authors: "Shruti Sharma, Papia Chowdhury"
        date: "2023"
        journal: "Materials Today: Proceedings"
        url: "https://doi.org/10.1016/j.matpr.2023.05.676"
        type: Proceedings
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: Data Analysis on Time-of-Flight study from the data files of Fermilab's to find Muon's Speed 
        url: "#"
        description: Data Analysis on Time-of-Flight study from the data files of Fermilab's to find Muon's Speed during International Muon Week. In this project we used the data of stacked detectors in Fermilab Location- Batavia, Illinois [ latitude- 41:52.193794 N, longitude- 087:38.902188 W (same for both)] which are placed at different positions upon each other. We determined the speed by calculating the inverse of the slopes of the best fit lines in scatter plots (where the independent variable is separation(m) and the dependent variable is mean traversal time (ns)). We compared our results for different pair of detectors. Looking at our results ,we concluded with our hypothesis to be true where muon speeds are found to be close to speed of light. 
      - title: Project
        url: "#"
        description: 
      - title: 
        url: "#"
        description: 
      - title: 
        url: "#"
        description: 
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "Skill 1, Skill 2"
        skillrating: 90
      - skill: Skill 3
        skillrating: 80
      - skill: Skill 4
        skillrating: 50
  hobby:
    title: Hobbies
    icon: fas fa-gamepad
    list:
      - hobby: Cooking
      - hobby: Hiking
      - hobby: Baking
  conference:
    title: Conferences
    icon: fas fa-book
    format:
      - date
      - title
      - authors
      - journal
    types:
      - Journal Articles
      - Proceedings
    list:
      - title: >-
          Harvesting Nature's Brilliance: Iron Ion (Fe3+) Sensing by Plumeria obtusa Leaf-Derived Carbon Quantum Dots.
        authors: "Shruti Sharma, Amisha Bhardwaj, Narayanan Venkatakrishnan, Papia Chowdhury"
        date: "2024"
        journal: "Arabian Journal for Science and Engineering"
        url: "https://doi.org/10.1007/s13369-024-09815-8"
        type: Journal Articles
      - title: >-
          Reactivities of 4-amino salicylic acid and its ‘Green’inhibition into nano sized β-cyclodextrin for Anti-Tuberculosis drug delivery.
        authors: "Shruti Sharma, Pooja Yadav, Meenakshi Rana, Papia Chowdhury"
        date: "2024"
        journal: "Journal of Molecular Liquids, 410, 125611"
        url: "https://doi.org/10.1016/j.molliq.2024.125611"
        type: Journal Articles
      - title: >-
          Photoluminescent carbon quantum dots synthesized from Plumeria leaves as metal ion sensor.
        authors: "Shruti Sharma, Papia Chowdhury"
        date: "2024"
        journal: "Bulletin of Materials Science 47 (3), 187"
        url: "https://doi.org/10.1007/s12034-024-03273-6"
        type: Journal Articles
      - title: >-
          Tunable dual photoluminescence from synthesized urea-based carbon quantum dots: A DFT based simulation on structural insights.
        authors: "Shruti Sharma, Papia Chowdhury"
        date: "2024"
        journal: "Optical Materials, 153, 115617"
        url: "https://doi.org/10.1016/j.optmat.2024.115617"
        type: Journal Articles
      - title: >-
          Thioglycolic acid capped CdSe/ZnS quantum dot as fluorescent sensor for the detection of water-soluble hazardous heavy metal ions.
        authors: "Shruti Sharma, Pooja Yadav, Papia Chowdhury"
        date: "2024"
        journal: "Applied Physics A 130 (5), 1-12"
        url: "https://doi.org/10.1007/s00339-024-07491-x"
        type: Journal Articles
      - title: >-
          Two-photon absorption and optical limiting in 7-diethylamino-4-methyl coumarin.
        authors: "Shradha Lakhera, Kamal Devlal, Meenakshi Rana, N Kanagathara, A Dhanusha, TC Sabari Girisun, Shruti Sharma, Papia Chowdhury"
        date: "2024"
        journal: "Journal of Photochemistry and Photobiology A: Chemistry 447, 115216"
        url: "https://doi.org/10.1016/j.jphotochem.2023.115216"
        type: Journal Articles
        type: Journal Articles
      - title: >-
          Exploring the nonlinear optical limiting activity of para-aminobenzoic acid by experimental and DFT approach.
        authors: "Shradha Lakhera, Meenakshi Rana, Kamal Devlal, Shruti Sharma, Papia Chowdhury, Vivek Dhuliya, Sagar Panwar, LP Purohit, A Dhanusha, TC Sabari Girisun"
        date: "2023"
        journal: "Journal of Photochemistry and Photobiology A: Chemistry, 444, 114987"
        url: "https://doi.org/10.1016/j.jphotochem.2023.114987"
        type: Journal Articles
      - 
        title: >-
          Fluorescence signal from carbon quantum dots synthesized from natural resources.
        authors: "Shruti Sharma, Papia Chowdhury"
        date: "2023"
        journal: "Materials Today: Proceedings"
        url: "https://doi.org/10.1016/j.matpr.2023.05.676"
        type: Proceedings
    publication:
    title: Publications
    icon: fas fa-book
    format:
      - date
      - title
      - authors
      - journal
    types:
      - Journal Articles
      - Proceedings
    list:
      - title: >-
          Harvesting Nature's Brilliance: Iron Ion (Fe3+) Sensing by Plumeria obtusa Leaf-Derived Carbon Quantum Dots.
        authors: "Shruti Sharma, Amisha Bhardwaj, Narayanan Venkatakrishnan, Papia Chowdhury"
        date: "2024"
        journal: "Arabian Journal for Science and Engineering"
        url: "https://doi.org/10.1007/s13369-024-09815-8"
        type: Journal Articles
      - title: >-
          Reactivities of 4-amino salicylic acid and its ‘Green’inhibition into nano sized β-cyclodextrin for Anti-Tuberculosis drug delivery.
        authors: "Shruti Sharma, Pooja Yadav, Meenakshi Rana, Papia Chowdhury"
        date: "2024"
        journal: "Journal of Molecular Liquids, 410, 125611"
        url: "https://doi.org/10.1016/j.molliq.2024.125611"
        type: Journal Articles
      - title: >-
          Photoluminescent carbon quantum dots synthesized from Plumeria leaves as metal ion sensor.
        authors: "Shruti Sharma, Papia Chowdhury"
        date: "2024"
        journal: "Bulletin of Materials Science 47 (3), 187"
        url: "https://doi.org/10.1007/s12034-024-03273-6"
        type: Journal Articles
      - title: >-
          Tunable dual photoluminescence from synthesized urea-based carbon quantum dots: A DFT based simulation on structural insights.
        authors: "Shruti Sharma, Papia Chowdhury"
        date: "2024"
        journal: "Optical Materials, 153, 115617"
        url: "https://doi.org/10.1016/j.optmat.2024.115617"
        type: Journal Articles
      - title: >-
          Thioglycolic acid capped CdSe/ZnS quantum dot as fluorescent sensor for the detection of water-soluble hazardous heavy metal ions.
        authors: "Shruti Sharma, Pooja Yadav, Papia Chowdhury"
        date: "2024"
        journal: "Applied Physics A 130 (5), 1-12"
        url: "https://doi.org/10.1007/s00339-024-07491-x"
        type: Journal Articles
      - title: >-
          Two-photon absorption and optical limiting in 7-diethylamino-4-methyl coumarin.
        authors: "Shradha Lakhera, Kamal Devlal, Meenakshi Rana, N Kanagathara, A Dhanusha, TC Sabari Girisun, Shruti Sharma, Papia Chowdhury"
        date: "2024"
        journal: "Journal of Photochemistry and Photobiology A: Chemistry 447, 115216"
        url: "https://doi.org/10.1016/j.jphotochem.2023.115216"
        type: Journal Articles
        type: Journal Articles
      - title: >-
          Exploring the nonlinear optical limiting activity of para-aminobenzoic acid by experimental and DFT approach.
        authors: "Shradha Lakhera, Meenakshi Rana, Kamal Devlal, Shruti Sharma, Papia Chowdhury, Vivek Dhuliya, Sagar Panwar, LP Purohit, A Dhanusha, TC Sabari Girisun"
        date: "2023"
        journal: "Journal of Photochemistry and Photobiology A: Chemistry, 444, 114987"
        url: "https://doi.org/10.1016/j.jphotochem.2023.114987"
        type: Journal Articles
      - 
        title: >-
          Fluorescence signal from carbon quantum dots synthesized from natural resources.
        authors: "Shruti Sharma, Papia Chowdhury"
        date: "2023"
        journal: "Materials Today: Proceedings"
        url: "https://doi.org/10.1016/j.matpr.2023.05.676"
        type: Proceedings
  